# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            lawson_y
tagline:          'Personal Blog'
description:      "Welcome to my Block"
url:              https://linfengwenyou.github.io/hydeout
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'linfengwenyou'
  url:            https://twitter.com/_LiuSong

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/linfengwenyou
